stages:
  - mirror

mirror-production-to-github:
  stage: mirror
  image: 
    name: alpine/git:latest
    entrypoint: [""]
  variables:
    GIT_STRATEGY: clone
    GIT_CHECKOUT: "false"
  script:
    # 1. Fetch only the production branch from GitLab
    - git fetch origin production:production --prune
    
    # 2. Set the remote using your GitLab Variable (GH_TOKEN)
    - git remote add github https://luitelsuman:${GH_TOKEN}@github.com/luitelsuman/mirror-gitlab-test.git || git remote set-url github https://luitelsuman:${GH_TOKEN}@github.com/luitelsuman/mirror-gitlab-test.git
    
    # 3. Push only the production branch to GitHub
    - git push github production --force
  rules:
    # 4. Only run this job when a push happens specifically to the production branch
    - if: $CI_COMMIT_BRANCH == "production"